/// Flutter icons BottomNavigation
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNavigation
///      fonts:
///       - asset: fonts/BottomNavigation.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomNavigation {
  BottomNavigation._();

  static const _kFontFam = 'BottomNavigation';
  static const _kFontPkg = null;

  static const IconData bloodglucose = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bloodgroup = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bloodpressure = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hemoglobin = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulserate = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
